version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: course_platform_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: course_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: dockerfile
    container_name: course_platform_backend
    restart: always
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/course_platform
      - NODE_ENV=production
      - JWT_SECRET=helloword
      - JWT_EXPIRES_IN=1d
      - JWT_REFRESH_EXPIRES_IN=7d
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  postgres_data:
